From zsh-workers-request@math.gatech.edu  Thu Aug 10 14:10:25 1995
Received: from gatech.edu (gatech.edu [130.207.244.244]) by werple.mira.net.au (8.6.12/8.6.9) with SMTP id OAA24799 for <mason@werple.mira.net.au>; Thu, 10 Aug 1995 14:10:19 +1000
Received: from math (math.skiles.gatech.edu) by gatech.edu with SMTP id AA09179
  (5.65c/Gatech-10.0-IDA for <mason@werple.mira.net.au>); Thu, 10 Aug 1995 00:08:46 -0400
Received: by math (5.x/SMI-SVR4)
	id AA02706; Thu, 10 Aug 1995 00:04:15 -0400
Resent-Date: Thu, 10 Aug 1995 11:57:14 +0800 (WST)
Old-Return-Path: <roy@cs.uwa.edu.au>
From: Roy LIMLEY <roy@cs.uwa.edu.au>
Message-Id: <199508100357.LAA11923@boodie.cs.uwa.oz.au>
Subject: zsh bugs
To: zsh-list@sterling.com
Date: Thu, 10 Aug 1995 11:57:14 +0800 (WST)
Cc: sean@boodie.cs.uwa.oz.au, chris@boodie.cs.uwa.oz.au,
        roy@boodie.cs.uwa.oz.au, james@boodie.cs.uwa.oz.au
X-Mailer: ELM [version 2.4 PL21]
Mime-Version: 1.0
Content-Type: text/plain; charset=US-ASCII
Content-Transfer-Encoding: 7bit
Resent-Message-Id: <"0cGeH1.0.Cg.-KOAm"@math>
Resent-From: zsh-workers@math.gatech.edu
X-Mailing-List: <zsh-workers@math.gatech.edu> archive/latest/301
X-Loop: zsh-workers@math.gatech.edu
Precedence: list
Resent-Sender: zsh-workers-request@math.gatech.edu

Dear Sir/Madam,

I was wondering if you can help me with a zsh (version 2.5.03) bug.  When we 
are running a zsh and then run another zsh on top of it.  Then if we exit
(by killing our X session) it automatically sends a SIGHUP to the first 
(parent) zsh and the second (child) zsh.  This will automatically kill the
second zsh, but not the first (we put a TRAPHUP to exit when the zsh got this 
signal).  The first zsh then become a wild process and consumes a fair bit of 
processing power.

Debugging it gave me some clue where it got stuck.  It got stuck in zle_main.c
source in line 254:

           while ( r=read(...... )
              if ( r == 0 ) {
                 if ( isset (IGNOREEOF ) )
                    continue;

My guess is that this process is trying to read a pipe from somewhere and keep
getting no message and then when it encounter the "continue" statement it
just loops back again and again,  which is what the debugger shows.

Is there already a patch to fix this problem or perhaps you can suggest a 
solution to us.  

Many thanks,

Roy Limley

