From zsh-users-return-14907-mason-zsh=primenet.com.au@zsh.org Sat Mar 06 22:09:20 2010
Return-Path: <zsh-users-return-14907-mason-zsh=primenet.com.au@zsh.org>
Delivered-To: mason-zsh@primenet.com.au
Received: (qmail 11671 invoked by alias); 6 Mar 2010 22:09:20 -0000
Mailing-List: contact zsh-users-help@zsh.org; run by ezmlm
Precedence: bulk
X-No-Archive: yes
List-Id: Zsh Users List <zsh-users.zsh.org>
List-Post: <mailto:zsh-users@zsh.org>
List-Help: <mailto:zsh-users-help@zsh.org>
Delivered-To: mailing list zsh-users@zsh.org
X-Seq: 14907
Received: (qmail 6937 invoked from network); 6 Mar 2010 22:09:18 -0000
X-Spam-Checker-Version: SpamAssassin 3.2.5 (2008-06-10) on f.primenet.com.au
X-Spam-Level: 
X-Spam-Status: No, score=-2.6 required=5.0 tests=AWL,BAYES_00 autolearn=ham
	version=3.2.5
Received-SPF: none (ns1.primenet.com.au: domain at closedmail.com does not designate permitted sender hosts)
From: Bart Schaefer <schaefer@brasslantern.com>
Message-id: <100306140858.ZM6830@torch.brasslantern.com>
Date: Sat, 06 Mar 2010 14:08:56 -0800
In-reply-to: <87y6i5b6vq.fsf@ft.bewatermyfriend.org>
Comments: In reply to Frank Terbeck <ft@bewatermyfriend.org>
 ""${(s.:.)foo} and rc_expand_param" (Mar  6,  8:13pm)
References: <87y6i5b6vq.fsf@ft.bewatermyfriend.org>
X-Mailer: OpenZMail Classic (0.9.2 24April2005)
To: zsh-users@zsh.org
Subject: Re: "${(s.:.)foo} and rc_expand_param
MIME-version: 1.0
Content-type: text/plain; charset=us-ascii

On Mar 6,  8:13pm, Frank Terbeck wrote:
} Subject: "${(s.:.)foo} and rc_expand_param
}
}   s:string:
}       For historical reasons, the usual behaviour that empty array
}       elements are retained inside double quotes is disabled for arrays
}       generated by splitting; hence the following:
} 
} zsh% setopt rc_expand_param
} zsh% print -l "${(s.:.)foo}"
} bar
} 
} baz
} 
} Am I missing something here or is this a bug?

I believe zsh is being faithful to the "rc" shell's behavior here.  The
doc note about "historical reasons" was added pretty recently, as was
the override of that behavor that's possible by using @s, so it's most
likely that there was always and intentionally this exception but that
it was missed when the doc was updated.

-- 

